### ISSUE TITLE
master spec tracker

### ISSUE THREAD

**Issue by squidgetx** [squidgetx/arklet-frick#8]
- [x] Resolver redirects ARKs to URLs
- [x] Resolver supports ?info and ?json inflection to return metadata (#1)
- [x] API endpoint to add new ARKs
- [x] API endpoint to update ARKs
- [x] Command line tool to add new ARKs (#5)
- [x] Command line tool to update new ARKs
- [x] Command line tool to query ARKs
- [x] Command line tool to bulk add new ARKs
- [x] Command line tool to bulk update new ARKs
- [x] Resolver supports shoulder rules
- [x] Resolver supports suffix pass-through
- [x] Resolver can be deployed separately from minter (#7 )
- [x] Minter uses Frick NAAN (this is configurable rn, but we should resolve this along with #9?)
- [x] Custom metadata schema can be amended (#3)
- [x] ARKS cannot be created without a pre-existing shoulder
- [ ] Performance audit

Deployment todos:
- [ ] Resolver uses ark.frick.org

**Comment by squidgetx** [comment]
Remaining todos (ordered roughly by priority)

- [x] Deployment
- [ ] Perf audit on DO hardware
- [x] API Docs
- [ ] Tests 
- [ ] Query by shoulder
